#!/bin/bash

rm -rf data.tar.gz control.tar.gz *.ipk *.deb
find . -name '*~' -delete
rm src/shared/data/www/meshchat/db/messages
rm -rf src/shared/data/www/meshchat/db/messages*
rm -rf src/shared/data/www/meshchat/db/action*
touch src/shared/data/www/meshchat/db/messages
chmod 666 src/shared/data/www/meshchat/db/messages

### Build AREDN package
export COPYFILE_DISABLE=1

cd src/shared/data
tar cf ../../../data.tar `find . -type f`
cd ../../node/data
tar rf ../../../data.tar `find . -type f`
cd ../control
tar cfz ../../../control.tar.gz .
cd ../../..
gzip data.tar
COPYFILE_DISABLE=1 tar cfz meshchat_1.02_all.ipk control.tar.gz data.tar.gz debian-binary

### Build AREDN API package
rm -rf data.tar.gz control.tar.gz

cd src/api/data
tar cf ../../../data.tar `find . -type f`
cd ../control
tar cfz ../../../control.tar.gz .
cd ../../..
gzip data.tar
COPYFILE_DISABLE=1 tar cfz meshchat-api_1.02_all.ipk control.tar.gz data.tar.gz debian-binary

### Build pi package
rm -rf data.tar.gz control.tar.gz

mkdir -p tmp/var/www/html
mkdir -p tmp/usr/lib/cgi-bin

cd src/shared/data
cp -R www/meshchat ../../../tmp/var/www/html/
cp -R usr ../../../tmp/
cp www/cgi-bin/* ../../../tmp/usr/lib/cgi-bin/

cd ../../pi/data
cp -R etc ../../../tmp/
cp -R usr ../../../tmp/
cp www/cgi-bin/* ../../../tmp/usr/lib/cgi-bin/

cd ../../../tmp
tar cfz ../data.tar.gz `find . -type f`

cd ../src/pi/control
tar cfz ../../../control.tar.gz .
cd ../../..
COPYFILE_DISABLE=1 ar r meshchat_1.02_all.deb debian-binary control.tar.gz data.tar.gz
rm -rf tmp
