#! /bin/sh

### BEGIN INIT INFO
# Provides:          meshchatsync
# Required-Start:    $local_fs 
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: meshchatsync
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

case "$1" in
  start)
    log_begin_msg "Starting meshchatsync"
    /usr/local/bin/meshchatsync > /dev/null 2>&1 &
    log_end_msg $?
    exit 0
    ;;
  stop)
    log_begin_msg "Stopping meshchatsync"

    killall meshchatsync > /dev/null

    log_end_msg $?
    exit 0
    ;;
  *)
    echo "Usage: /etc/init.d/meshchatsync {start|stop}"
    exit 1
    ;;
esac
