#!/bin/sh

/etc/init.d/meshchatsync stop > /dev/null 2>&1

update-rc.d -f meshchatsync remove > /dev/null 2>&1

rm -rf /tmp/meshchat
#rm -rf /var/www/html/meshchat/files
#rm -rf /var/www/meshchat

exit 0
