#!/bin/sh

/etc/init.d/meshchatsync disable
/etc/init.d/meshchatsync stop

rm -rf /tmp/messages
rm -rf /tmp/remote_messages
rm -rf /tmp/sync_status
rm -rf /tmp/meshchat_users_local
rm -rf /tmp/meshchat_users_remote

exit 0
